name: Example

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: k1LoW/phan-action@v0
        with:
          config-file: testdata/.phan/config.php
