name: Integration

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          allow-failure: true
          config-file: testdata/.phan/config.php
